image: docker:20.10.3-dind

services:
  - docker:dind

stages:
  - build

build_golang_cli:
  stage: build
  #image: golang:1.15.8-buster
  before_script:
    - apk update && apk add go
    - go version
    #- go get -d github.com/c-bata/go-prompt
    - docker login -u ${DOCKERHUB_NAMESPACE} -p ${DOCKERHUB_ACCESSTOKEN}
    - docker info
  script:
    - go build -o webserver
    - go clean
    #
    - ./webserver & curl localhost:8083/ciao
    #
    - docker build -t go_webserver .
    - docker tag ${DOCKERHUB_NAMESPACE}
    - docker tag go_webserver ${DOCKERHUB_NAMESPACE}/go_webserver
    - docker push ${DOCKERHUB_NAMESPACE}/go_webserver
  #tags:
  #  - hetzner
  only: 
    - master
